name: arcore_flutter_plugin
description: Flutter plugin for ARCore SDK, Android platform to build new augmented reality experiences
version: 0.0.6+2
homepage: https://github.com/giandifra/arcore_flutter_plugin

environment:
  sdk: '>=2.3.0 <3.0.0'
  flutter: ">=1.10.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  vector_math: ^2.0.8
  meta: ^1.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
  plugin:
    platforms:
      android:
        package: com.difrancescogianmarco.arcore_flutter_plugin
        pluginClass: ArcoreFlutterPlugin
  